language: go
sudo: false

env:
  global:
    - GOLANGCI_LINT_VERSION=v1.10.2

matrix:
  allow_failures:
    - go: master
  include:
    # Supported versions of Go: https://golang.org/dl/
    - go: "1.10.x"
    - go: "1.11.x"
    - go: master

before_install:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $GOPATH/bin $GOLANGCI_LINT_VERSION

before_script:
  - golangci-lint run

script:
  - go test -v -race -coverprofile=coverage.txt

after_success:
  - bash <(curl -s https://codecov.io/bash) -X fix
